services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /healthz
    envVars:
      - key: TELEGRAM_TOKENS
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: TZ
        value: Asia/Ho_Chi_Minh
      - key: PYTHON_VERSION
        value: 3.12.2
